order_cancel:
    path: /orders/{orderId}/cancel
    controller: App\Presentation\Controller\OrderController::cancelOrder
    methods: [POST]

order_search_by_customer:
    path: /orders/customer
    controller: App\Presentation\Controller\OrderController::searchByCustomerName
    methods: [POST]

order_search_by_status:
    path: /orders/status
    controller: App\Presentation\Controller\OrderController::searchByStatus
    methods: [POST]

order_search_by_id:
    path: /orders/{orderId}
    controller: App\Presentation\Controller\OrderController::findById
    methods: [GET]

order_search:
    path: /orders
    controller: App\Presentation\Controller\OrderController::getOrders
    methods: [GET]