order_cancel:
    path: /orders/{order_id}/cancel
    controller: App\Presentation\Controller\OrderController::cancelOrder

order_search:
    path: /orders/search
    controller: App\Presentation\Controller\OrderController::searchOrders

order_search_customer:
    path: /orders/search/customer
    controller: App\Presentation\Controller\OrderController::searchOrdersByCustomerName
    methods: [POST]


order_paginate:
    path: /orders/page/{page}
    controller: App\Presentation\Controller\OrderController::paginateOrders