#index:
#    path: /
#    controller: App\Controller\DefaultController::index

order_cancel:
    path: /orders/{id}/cancel
    controller: App\Presentation\Controller\OrderController::cancelOrder

order_search:
    path: /orders/search
    controller: App\Presentation\Controller\OrderController::searchOrders

order_paginate:
    path: /orders/page/{page}
    controller: App\Presentation\Controller\OrderController::paginateOrders