order_cancel:
    path: /orders/{orderId}/cancel
    controller: App\Presentation\Controller\OrderController::cancelOrder
    methods: [GET]

order_search_customer:
    path: /orders/search/customer
    controller: App\Presentation\Controller\OrderController::searchByCustomerName
    methods: [POST]

order_search_by_id:
    path: /orders/{orderId}
    controller: App\Presentation\Controller\OrderController::findById
    methods: [GET]

order_search:
    path: /orders/page/{page}
    controller: App\Presentation\Controller\OrderController::paginateOrders
    methods: [GET]